Creating the Array in Using Numpy

In [5]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [2]:
list=[1,2,3,4.5,"Hello"]

In [3]:
np.array(list)

array(['1', '2', '3', '4.5', 'Hello'], dtype='<U32')

In [4]:
list=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generating Functions

In [9]:
arr=np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [13]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Lin Space calculate the value to be added to each other :
linspace=(stop-start)/(num-1)

In [21]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Functions

In [28]:
arr=np.random.rand(3)
arr

array([0.57931897, 0.71327461, 0.94308828])

In [31]:
arr=np.random.randn(10)
arr

array([ 0.21043447,  0.12951091, -0.07037157,  0.14718923, -0.06055876,
        0.78712713,  0.0237429 , -0.43793321,  0.00735705, -1.02028486])

In [39]:
arr=np.random.randint(3,10,2)
arr
print(arr)

[7 3]


Array Attributes

In [54]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
print(arr.shape)

(3, 3)


In [51]:
print(arr.dtype)

int64


In [47]:
print(arr.size)

9


Array Methods ()

In [49]:
print(arr.min())

1


In [50]:
print(arr.max())

9


In [52]:
print(arr.sum())

45


In [ ]:
np.sum(arr,axis=0) #Column SUm

array([12, 15, 18])

In [55]:
np.sum(arr,axis=1)# Row sum

array([ 6, 15, 24])

In [57]:
print(arr.mean())

5.0


In [59]:
print(arr.std())

2.581988897471611


In [60]:
print(arr.argmin())

0


In [ ]:
print(arr.argmax())# return the index of max element

8


Converting a one-D array into 2-D Matrix using reshape

In [7]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [9]:
print(arr.reshape(5,6))  # there are 30 element so only product of 30 matrix can be made like 6x5 or 5x6


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


The End