NUMPY Indexing and Slicing of Vector-1D

In [1]:
import numpy as np

In [3]:
arr=np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
print(arr[::3])

[0 3 6 9]


NUMPY Indexing and Slicing of Matrix-2D

In [12]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
print(arr[3,3])

19


In [17]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

Bool Indexing

In [20]:
bool_index=arr %2==0
bool_index

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [23]:
EvenValue=arr[bool_index]
print(EvenValue)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


The End