<h3>Array Arthmetics</h3>

In [12]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [3]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [4]:
arr2/arr1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [5]:
arr2//arr1

array([6, 3, 2, 2, 2])

In [6]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [7]:
arr2**arr1

array([     6,     49,    512,   6561, 100000])

<h3>Array Broadcasting</h3>

In [8]:
arr1+10

array([11, 12, 13, 14, 15])

In [10]:
newArr=np.arange(1,26).reshape(5,5)
newArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
newArr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

<h3>Deep copy and Shallow copy</h3>

In [13]:
A=np.array([1,2,3,4,5])

In [14]:
B=A

In [15]:
B[0]=12

In [16]:
A

array([12,  2,  3,  4,  5])

In [17]:
B #Changing with B reflect changes in A its a shallow copy

array([12,  2,  3,  4,  5])

In [18]:
A=np.array([1,2,3,4,5])

In [19]:
B=np.copy(A)

In [20]:
B[0]=12

In [21]:
B

array([12,  2,  3,  4,  5])

In [22]:
A # A array element are same this is deep copy

array([1, 2, 3, 4, 5])

<h3>Matrix operations </h3>

In [28]:
matx1=np.arange(1,5).reshape(2,2)
matx1

array([[1, 2],
       [3, 4]])

In [29]:
matx2=np.arange(1,5).reshape(2,2)
matx2

array([[1, 2],
       [3, 4]])

In [30]:
matx1@matx2

array([[ 7, 10],
       [15, 22]])

In [31]:
np.dot(matx1,matx2)

array([[ 7, 10],
       [15, 22]])

In [32]:
matx1.T

array([[1, 3],
       [2, 4]])

<h3>Array Stacking</h3>

Array stacking doest not work on 2D Matrix

In [37]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)

In [38]:
np.hstack((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [40]:
np.column_stack((arr1,arr2))

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

<h3>Array Splitting</h3>

In [50]:
myArr=np.arange(1,61).reshape(10,6)
print(myArr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [52]:
print(np.hsplit(myArr,2))

[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27],
       [31, 32, 33],
       [37, 38, 39],
       [43, 44, 45],
       [49, 50, 51],
       [55, 56, 57]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36],
       [40, 41, 42],
       [46, 47, 48],
       [52, 53, 54],
       [58, 59, 60]])]


In [53]:
print(np.vsplit(myArr,5))

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]]), array([[37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]]), array([[49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])]
