Creating the Array in Using Numpy

In [1]:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [2]:
list=[1,2,3,4.5,"Hello"]

In [3]:
np.array(list)

array(['1', '2', '3', '4.5', 'Hello'], dtype='<U32')

In [4]:
list=[[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generating Functions

In [9]:
arr=np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [13]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Lin Space calculate the value to be added to each other :
linspace=(stop-start)/(num-1)

In [21]:
arr=np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Functions

In [28]:
arr=np.random.rand(3)
arr

array([0.57931897, 0.71327461, 0.94308828])

In [31]:
arr=np.random.randn(10)
arr

array([ 0.21043447,  0.12951091, -0.07037157,  0.14718923, -0.06055876,
        0.78712713,  0.0237429 , -0.43793321,  0.00735705, -1.02028486])

In [39]:
arr=np.random.randint(3,10,2)
arr
print(arr)

[7 3]


Array Attributes

In [45]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
print(arr.shape)

(3, 3)


In [47]:
print(arr.size)

9


Array Methods ()

In [49]:
print(arr.min())

1


In [50]:
print(arr.max())

9
